// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Voltage.Witches.Util
{
	public static class EnumerableHelpers
	{
		public static void Each<T>(this IEnumerable<T> collection, Action<T, int> action)
		{
			int i = 0;
			foreach (T element in collection)
			{
				action(element, i);
				++i;
			}
		}
	}
}

